### ISSUE TITLE
Error - Could not pass event onArmorStandRemove to ArmorStand-Limiter v1.6

### ISSUE THREAD

**Issue by BartosB13** [xSavior-of-God/ArmorStand-Limiter#7]
- Paper 1.19.3
- ArmorStand-Limiter v1.6
- ModelEngine R3.1.6

```
[10:08:44 ERROR]: Could not pass event onArmorStandRemove to ArmorStand-Limiter v1.6
java.lang.NoSuchMethodError: 'com.ticxo.modelengine.api.manager.ModelManager com.ticxo.modelengine.api.ModelEngineAPI.getModelManager()'
        at com.xSavior_of_God.ArmorStandLimiter.externals.ModelEngine.onArmorStandRemove(ModelEngine.java:19) ~[ArmorStand-Limiter.v1.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1295.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at com.xSavior_of_God.ArmorStandLimiter.Utilis$1.run(Utilis.java:80) ~[ArmorStand-Limiter.v1.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin
```

**Comment by BartosB13** [comment]
Hello, sorry for asking. Can you estimate when roughly the update might be released?

**Comment by xSavior-of-God** [comment]
Hi @BartosB13, sorry for late, tomorrow if all goes well I will complete the test phase and fix the build.

**Comment by BartosB13** [comment]
ok thanks

**Comment by xSavior-of-God** [comment]
Solved.
